-- Day 3: WHERE, DELETE, ALTER & DROP

-- WHERE Clause
SELECT * FROM EMPLOYEE WHERE DEPARTMENT = 'DATA SCIENCE';
SELECT * FROM EMPLOYEE WHERE SALARY > 55000;
SELECT * FROM EMPLOYEE WHERE POSITION = 'DATA ANALYST' AND SALARY = 60000;

-- DELETE Command
DELETE FROM EMPLOYEE WHERE emp_id = 6;
DELETE FROM EMPLOYEE WHERE POSITION = 'DATA ANALYST';

-- ALTER Command
ALTER TABLE EMPLOYEE ADD email VARCHAR(100);
ALTER TABLE EMPLOYEE RENAME COLUMN name TO full_name;
ALTER TABLE EMPLOYEE DROP COLUMN email;

-- DROP Command
DROP TABLE IF EXISTS EMPLOYEE;
