SELECT *
FROM EMPLOYEE2
WHERE AGE = 30;

--matches all except 30
SELECT FIRST_NAME, AGE
FROM EMPLOYEE2
WHERE AGE != 30;

--salary greater than 50000
SELECT FIRST_NAME, SALARY
FROM EMPLOYEE2
WHERE SALARY >= 50000;
