-- BASIC SELECT
SELECT * FROM EMPLOYEE2;

-- USING AND OPERATOR
SELECT * FROM EMPLOYEE2
WHERE AGE >= 40
AND SALARY >= 50000;

-- USING OR OPERATOR
SELECT * FROM EMPLOYEE2
WHERE AGE >= 40
OR SALARY >= 50000;

-- USING NOT OPERATOR
SELECT * FROM EMPLOYEE2
WHERE NOT (DEPARTMENTS = 'IT');
